# Generated by Django 2.1.5 on 2019-02-07 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('book', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('slug', models.SlugField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookStore.Author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookStore.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='genre',
            field=models.ManyToManyField(to='BookStore.Genre'),
        ),
    ]
